#! /usr/bin/python

#
# A rough skbtrace results parsing demo
#

import getopt
import sys
import os
import time
import glob
import struct
import re

from util import *
import events_common
import events_ipv4

SKBPARSE_VERSION = "0.1.0"
SKBTRACE_BLOCK_MAGIC = 0xDEADBEEF

Action_table = {}

class EOF(OSError):
	pass

class unknown_block:
	def __init__(self, block, trace):
		self.blk = block
		size = block.len - block.common_header_size()
		self.data = trace.read(size)
		if size < 0 or block.magic != SKBTRACE_BLOCK_MAGIC:
			s = str(block)
			s += str(self)
			raise RuntimeError, "unknown_block: invalid block: '%s'" % s

	def __str__(self):
		s = "action=unknown(%d)" % self.blk.action
		s += " magic=%x len=%d ptr=0x%x flags=0x%x data(%d bytes)=%s" % \
						(self.blk.magic, self.blk.len, self.blk.ptr, \
						self.blk.flags, len(self.data), `self.data[:128]`)
		return s

class skbtrace_block:
	flags = {
		1<<28 : "miss-snd-blocks,"
	}
	def __init__(self, trace, channel, cpu):
		global Action_table
		self.channel = channel
		self.cpu = cpu
		self.len = 0
		self.action = 0
		self.flags = 0
		self.ts = None
        	self.seq = 0
		self.ptr = 0
		self.__load(trace)
		event_class_list = Action_table.get(self.action, [unknown_block])
		for event_class in event_class_list:
			try:
				self.event2 = event_class(self, trace)
				break
			except ValueError:
				trace.seek(-block.len, 1)
				self.event2 = None

	def common_header_size(self):
		s = struct.calcsize("L") # magic
		s += struct.calcsize("H") # len
		s += struct.calcsize("H") # action
		s += struct.calcsize("I") # flags
		s += struct.calcsize("LL") # ts
		s += struct.calcsize("L") # seq
		s += struct.calcsize("P") # ptr
		return s

	def __load(self, trace):
		size = self.common_header_size()
		binary = trace.read(size)
		if not binary:
			raise EOF, "EOF %s,cpu%s" % (self.channel, self.cpu)

		fmt = "LHHILLLL"
		self.magic, self.len, self.action, self.flags, self.sec, self.nsec, \
			self.seq, self.ptr = struct.unpack(fmt, binary)
		common_flags = self.flags & 0xf0000000
		self.flags &= ~(0xf0000000)
		self.desc = ""
		for f in skbtrace_block.flags:
			if f & common_flags:
				self.desc += skbtrace_block.flags[f]

	def __str__(self):
		s = "%ld %ld.%ld " % (self.seq, self.sec, self.nsec)
		if conf("detail"):
			s += "cpu=%s channel=%s " % (self.cpu, self.channel)
		if self.desc:
			s += "flags=" + self.desc[:-1] + " "
		try:
			s += str(self.event2)
		except AttributeError:
			pass
		return s

	def __cmp__(self, other):
		if self.seq < other.seq:
			return -1
		elif self.seq > other.seq:
			return 1
		return 0

def setup_conf_table(conf_table, key, value):
	if value:
		conf_table[key] = value
	else:
		conf_table[key] = False

def conf(name):
	global Conf_table
	return Conf_table[name]

def show_version(*args):
	print sys.argv[0], "version", SKBPARSE_VERSION
	sys.exit(0)

def show_help(conf_table, *args):
	global Opt_parse_table
	print sys.argv[0], "version", SKBPARSE_VERSION
	print "Usage:"
	for option in Opt_parse_table:
		has_arg, conf_name, msg, callback = Opt_parse_table.get(option)
		if has_arg:
			arg = "ARG"
		else:
			arg = ""
		line = "\t%s %s\t%s" % (option, arg, msg)
		print line
	sys.exit(0)

def option(has_arg, key, default, help, handler = setup_conf_table):
	global Conf_table
	if key:
		Conf_table[key] = default
	return (has_arg, key, help, handler)

Conf_table = {}
Opt_parse_table = {
	"-i" : option(True,  "input-dir",  "./skbtrace.results",   "The results directory that skbtrace utility generated"),
	"-o" : option(True,  "output-fn", "./skbparse.results",   "The results filename that skbparse will generate"),
	"-V" : option(False, "verbose",    False, "Show more runtime configuration information"),
	"-d" : option(False, "detail",     False,  "Show more details in output of parsed events"),
	"-r" : option(False, "real-time",  False,  "Real-time mode, which works together with -s option of skbtrace"),
	"-S" : option(False, "stdout",     None,  "Write parsed result on stdout"),
	"-h" : option(False, "",           None,  "Show usage information", show_help),
	"-v" : option(False, "",           None,  "Show version information", show_version),
}

def handle_args(args):
	global Opt_parse_table, Conf_table
	try:
		opt_string = ""
		for option in Opt_parse_table:
			has_arg, conf_name, msg, callback = Opt_parse_table.get(option)
			opt_string += option[1]
			if has_arg:
				opt_string += ":"
		getopt_list = getopt.getopt(args, opt_string)
	except getopt.GetoptError:
		show_help(Conf_table)
	if getopt_list[1]:
		show_help(Conf_table)
	for key, value in getopt_list[0]:
		has_arg, conf_name, msg, callback = Opt_parse_table.get(key)
		if not has_arg:
			value = True
		callback(Conf_table, conf_name, value)

def should_stop():
	real_time = conf("real-time") # TODO
	return True

def skbparse(if_list, out_f):
	n_if_list = len(if_list)
	trace_info_list = []
	reg = re.compile(".*trace\.(?P<channel>((hardirq)|(softirq)|(syscall)))\.cpu(?P<cpu>[0-9]+)")
	try:
		for i in range(n_if_list):
			in_f = if_list[i]
			channel = reg.match(in_f.name).groupdict()["channel"]
			cpu = reg.match(in_f.name).groupdict()["cpu"]
			trace_info_list.append((in_f, channel, cpu))
		try:
			all_eof = False
			while not all_eof:
				all_eof = True
				for in_f, channel, cpu in trace_info_list:
					try:
						blk = skbtrace_block(in_f, channel, cpu)
						out_f.write(str(blk) + "\n")
						all_eof = False
					except EOF:
						pass
		except KeyboardInterrupt:
			sys.stderr.write("\nCtrl-C interrupted\n")
	finally:
		for i in range(n_if_list):
			in_f = if_list[i]
			in_f.close()
		out_f.close()

def setup_action_table():
	for m in (events_common, events_ipv4):
		for e in m.events_list:
			event_class_list = Action_table.get(e.action, [])
			event_class_list.append(e)
			Action_table[e.action] = event_class_list

def open_input():
	input_dir = conf("input-dir")
	hw = glob.glob(input_dir + "/trace.hardirq.cpu*")
	si = glob.glob(input_dir + "/trace.softirq.cpu*")
	sc = glob.glob(input_dir + "/trace.syscall.cpu*")
	results = hw + si + sc
	if not results:
		print "Can't find skbtrace results in", input_dir
		sys.exit(1)
	if_list = []
	for f in results:
		if_list.append(open_file(f, "r"))
	return if_list

def open_output():
	if conf("stdout"):
		return sys.stdout
	return open_file(conf("output-fn"), "w")

if __name__ == "__main__":
	setup_action_table()
	handle_args(sys.argv[1:])
	if_list = open_input()
	of = open_output()
	if conf("verbose"):
		print "skbtrace result files:"
		map(lambda x: sys.stdout.write("\t" + x.name + "\n"), if_list)
		print "skbparse result file:", of.name
	skbparse(if_list, of)
	of.close()
	sort = "sort -n %s > %s.sort" % (of.name, of.name)
	os.system(sort)
